---
d6system:
  achievements:
    d6_roll:
      type: d6
      message: Rolled an ability.
    d6_fate_spent:
      type: d6
      message: Spent a fate point when making a roll.
  cg_creation_points: 79
  cp_cron:
    day_of_week:
    - Sat
    hour:
    - 21
    minute:
    - 0
  max_char_hoard: 70
  max_fate_hoard: 10
  periodic_cp: 2
  sheet_columns:
  - Reflexes Presence
  - Physique Coordination Extranormal
  - Knowledge Perception
  show_sheet: true
  starting_char_points: 1
  starting_fate_points: 3
  shortcuts:
    wounds: wound/list
    wounded: wound/list

