---
d6system:
  assist_heal_block: 24
  assist_healed_cron:
    minute:
    - 0
    - 30
  heal_skills:
  - name: Medicine
    modifier: 0
  - name: Healing
    modifier: 0
  natural_heal_cron:
    minute:
    - 15
    - 45
  natural_heal_message: You can do this from the job menu of the webportal. You'll
    have to roll  'Physique' against the difficulty specified above. Please take into
    account  that to make this roll without negative modifiers, your char would have
    to  have rested in the required time span. Light activity means a negative  modifier
    of -1D, full activity a negative   modifier of -2D. Also, if you  have any special
    abilities, advantages or disadvantages that imply further  modifiers, you can
    apply them to your roll as well.%r%rIf you need help adding the roll, please contact
    admin for assistance.
  permissions:
    manage_damage: Can set wound levels on characters.
  wound_levels:
  - name: Fully Healed
    effect: Character is at full health.
  - name: Stunned
    effect: Add a -1D modifier for this round and the next.
    assist_diff: 10
  - name: Wounded
    effect: Add a -1D modifier to your rolls.
    rest_period: 3
    assist_diff: 15
    natural_diff: 6
  - name: Severely Wounded
    effect: Add a -2D modifier to your rolls.
    rest_period: 3
    assist_diff: 15
    natural_diff: 6
  - name: Incapacitated
    effect: Add a -3D modifier to your rolls.
    rest_period: 14
    assist_diff: 20
    natural_diff: 8
  - name: Mortally Wounded
    effect: near death and knocked unconscious.
    rest_period: 35
    assist_diff: 30
    natural_diff: 8
  - name: Dead
    effect: As it says in the title.
  wound_levels_blurb: Listed below are the wound levels of this game, sorted by their
    severity.  Stunned is a special case, as it only affects a character for a brief
    time  (1-2 rounds). For any wounded state, a healer would use the in game 'heal'
    command to treat a wounded person (which would trigger a roll of their healing  ability
    against the assisted heal difficulty). Without any assisted treatment,  the character
    will have to rely on natural healing alone. See the required  rest time below,
    after which a job will be triggered to handle the process of  natural healing.
    The character will need to roll Physique then, probably with  respective modifiers,
    against the natural heal difficulty. You can spend a character point and / or
    a fate point on your roll. Each successful treatment will improve the character's
    state by one level. A critical failure on the treatment however will lower the
    character's state by one level. Please check advantages, disadvantages and special
    abilities, as they might affect your roll.
  wounds_fields:
  - field: name
    width: 16
    title: Name
  - field: wound_level
    width: 21
    title: Wound Level
  - field: wound_updated
    width: 23
    title: Last Updated
  - field: healed_by
    width: 16
    title: Healed by
